import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
//Srcs
import "./globals.css";
import "../components/welcomepage.scss"
import "./AutoImage/autoimage.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Invitation App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
