import { Inter } from "next/font/google";
import { ChakraProvider, Box } from "@chakra-ui/react";
//Scss
import "./globals.css";
import "./layout.scss";
import "./home.scss";
import "../components/footer.scss";
import "./Introduction/intoduction.scss";
import "./Agenda/agenda.scss";
import "./Wish/wish.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Invitation App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <div className="layout-container">
            <Box className="box-container">{children}</Box>
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
